### PR TITLE
This fixes a bug with camelCased flattened keys

### PR DESCRIPTION
**Pull request by fringd**
i was unparsing paths.somePath and paths.some-path and getting duplicates.

this seems to fix it.

### CODE REVIEW

**Comment by fringd** [comment]
@bcoe hey love the package. No stress, just pinging to make sure this doesn't get lost in the noise of greenkeeper PRs

**Comment by bcoe** [comment]
@fringd :wave: heyo, sorry this is a bit of an orphan these days I think; because @satazor and I are both so darn busy.

This looks quite reasonable to me, perhaps join the tooling chat and we can work on getting a yargs-unparser release out the door soon:

http://devtoolscommunity.herokuapp.com/

**Comment by fringd** [comment]
a release is all well and good, but why not just merge this PR in the mean time?

**Comment by satazor** [comment]
Sorry for the delay, this lgtm. Feel free to merge @bcoe!

**Comment by bcoe** [comment]
@fringd want to take `npm i yargs-unparser@next` for a spin, and let me know if it does the trick or you; I'll promote it to latest soon.

**Pull request merged**
